services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Bảo toàn node_modules sinh ra trong container
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    command: sh -c "composer install && php artisan key:generate --force && php artisan migrate --force && apache2-foreground"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=notes_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: notes_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      # Mount folder dữ liệu cố định tránh mất sau mỗi lần khởi động
      - ./docker/mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Dashboard UI
      - "1025:1025" # SMTP server
